[project]
name = "deepstock"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "pytest>=8.3.5",
    "ruff>=0.11.0",
    "streamlit>=1.43.2",
]
